services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: cadastro
      POSTGRES_PASSWORD: cadastro
      POSTGRES_DB: cadastro
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    environment:
      DATABASE_URL: postgresql+psycopg2://cadastro:cadastro@db:5432/cadastro
      JWT_SECRET: "troque-esta-chave"
      JWT_ALG: "HS256"
      ACCESS_TOKEN_EXPIRE_MINUTES: "120"
      CORS_ORIGINS: "http://localhost:3000,http://localhost:5173"
      UPLOAD_DIR: "/app/uploads"
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - uploads:/app/uploads

volumes:
  pgdata:
  uploads:
